language: minimal
dist: focal

env:
  global:
    - ALPINE_VER="latest-stable"

install: true

script:
  - ./build.sh

after_script:
  - docker images

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: docker push "${DOCKER_USERNAME}/alpine:${ALPINE_VER}"
  on:
    branch: main
